# Generated by Django 5.0 on 2024-01-02 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('polls', '0002_mycustomuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='myCustomUser',
            new_name='CustomUser',
        ),
    ]
