# Generated by Django 5.0 on 2024-01-02 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_alter_vote_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='votes_count',
            field=models.IntegerField(default=0),
        ),
    ]
