# Generated by Django 5.0 on 2024-01-02 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_customuser_votes_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vote',
            name='count',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
