# Generated by Django 5.0 on 2024-01-02 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_choice_count_vote_count'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('user', 'question')},
        ),
        migrations.RemoveField(
            model_name='vote',
            name='count',
        ),
    ]
