# Generated by Django 5.0 on 2024-01-02 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_alter_vote_unique_together_remove_vote_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='count',
        ),
        migrations.AddField(
            model_name='vote',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
