# Generated by Django 5.0 on 2024-01-02 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_remove_choice_count_vote_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
