# Generated by Django 5.0 on 2024-01-02 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_choice_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='count',
        ),
    ]
