# Generated by Django 5.0 on 2024-01-02 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_remove_vote_count_choice_count_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='choice',
            name='count',
        ),
        migrations.AddField(
            model_name='vote',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
