# Generated by Django 5.0 on 2024-01-02 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_alter_vote_unique_together_remove_choice_count_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('user', 'question')},
        ),
    ]
